apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6bu5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6bu5
    app.kubernetes.io/part-of: ci1t-830-0027-app
  name: devfile-sample-6bu5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6bu5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6bu5
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0027-tenant/ci1t-830-0027-app/devfile-sample-6bu5@sha256:4223ed7786ce002a9a2f9859ad231535ee5c743cf5ad9e8289745d5db2591036
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
